language: php
php:
    - 7.0
    - 5.6

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --no-interaction

script:
    - vendor/bin/phpcs --standard=PSR2 --extensions=php --ignore=*/vendor/* . 
    - mkdir -p build/logs
    - vendor/bin/phpunit

after_script:
    - vendor/bin/coveralls --no-interaction
